### ISSUE TITLE
O Souto é bom professor. Noções por favor

### ISSUE THREAD

**Issue by luist18** [FlyHigh1111/FEUP-MIEIC#3]

**Comment by bdmendes** [comment]
Bump

**Comment by biromiro** [comment]
😳 😳

**Comment by kat-maq** [comment]
Souto não é o melhor prof do Mieic, mas também não se pode comparar com o MikeG ok

**Comment by FlyHigh1111** [comment]
@luist18 argumentos a favor disso por favor. @kat-maq o mikeG ao menos deu-nos 100% nas fichas, o souto deu-nos dois testes para fazer com erros no enunciado. Ainda fico na dúvida de quem é pior

**Comment by jfbaltazar** [comment]
o Souto merdou e depois desenmerdou, pelo menos grande parte. teve até, arrisco-me a dizer, momentos fofos de lés a lés.
por outro lado, o xenófobo preguiçoso do miguel não só foi isso mesmo, xenófobo e preguiçoso, como não mostrou qualquer vontade de flexibilizar, estar do nosso lado ou remendar problemas. não gostei do souto principalmente pela forma como organiza e planifica a cadeira, mas não tenho dúvidas sobre quem é o pior.

**Comment by luist18** [comment]
Depois desta modesta discussão em que chegamos à conclusão que, de facto, o Souto é bom professor dou o verídicto como encontrado: o Souto é bom professor. Agradeço todas as respostas 🙏🏼

**Comment by biromiro** [comment]
W
